version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      python: 3.12
    commands:
      - set -e
      - echo "✅ Installing AWS SAM CLI"
      - pip install aws-sam-cli

  pre_build:
    commands:
      - echo "🔐 Logging into Amazon ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 151182332702.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=latest
      - ECR_REPO=151182332702.dkr.ecr.us-east-1.amazonaws.com/akmal/webapp
      - CONTAINER_NAME=akmal-webapp

  build:
    commands:
      - echo "🛠 Building Docker image"
      - cd regioninfo
      - chmod +x ./gradlew || true
      - ./gradlew build
      - docker build -t akmal/webapp .
      - docker tag akmal/webapp:latest $ECR_REPO:$IMAGE_TAG
      - cd ../aws-cicd-notification
      - echo "📦 Building and packaging Lambda"
      - sam build --template-file uploads_notification/template.yaml
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket akmal-makhmudov-bucket --output-template-file uploads_notification/packaged.yaml
      - cd ../  # back to root

  post_build:
    commands:
        - echo "🚀 Pushing Docker image to ECR"
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo "📄 Creating imagedefinitions.json"
      - echo "[{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$ECR_REPO:$IMAGE_TAG\"}]" > imagedefinitions.json
      - echo "✅ Deployment build complete!"

      # - echo "🚀 Pushing Docker image to ECR"
      # - docker push $ECR_REPO:$IMAGE_TAG
      # - echo "📄 Creating imagedefinitions.json"
      # - echo "[{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$ECR_REPO:$IMAGE_TAG\"}]" > imagedefinitions.json
      # - echo "📤 Deploying ECS Fargate + RDS stack"
      # - aws cloudformation deploy \
      #     --template-file main-stack-final.yaml \
      #     --stack-name akmal-ecs-fargate-stack \
      #     --capabilities CAPABILITY_NAMED_IAM \
      #     --parameter-overrides \
      #         ImageUrl=$ECR_REPO:$IMAGE_TAG \
      #         DBUsername=admin \
      #         DBPassword=Admin123$ \
      #         VPC=vpc-03b0687b56e5e4284 \
      #         PublicSubnetA=subnet-0c54a03469761cbd2 \
      #         PublicSubnetB=subnet-06743ac42e7cf5ad8 \
      #         PrivateSubnetA=subnet-08fde9a496b874bec \
      #         PrivateSubnetB=subnet-0f75970e73d049f61
      # - echo "✅ Deployment complete!"

artifacts:
  base-directory: .
  files:
    - aws-cicd-notification/uploads_notification/packaged.yaml
    - imagedefinitions.json
