version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      python: 3.12
    commands:
      - echo "✅ Installing SAM CLI"
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "🔧 Logging in to Amazon ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 151182332702.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "🚧 Building Spring Boot Docker image"
      - cd regioninfo
      - ./gradlew build
      - docker build -t akmal/webapp .
      - docker tag akmal/webapp:latest 151182332702.dkr.ecr.us-east-1.amazonaws.com/akmal/webapp:latest
      - cd ../aws-cicd-notification
      - echo "🧱 Building and packaging Lambda"
      - sam build
      - sam package \
          --template-file template.yaml \
          --s3-bucket akmal-makhmudov-bucket \
          --output-template-file packaged.yaml
  post_build:
    commands:
      - echo "📦 Pushing Docker image to ECR"
      - docker push 151182332702.dkr.ecr.us-east-1.amazonaws.com/akmal/webapp:latest
artifacts:
  files:
    - aws-cicd-notification/packaged.yaml
