AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Service (Public) with ALB and MySQL RDS (Private)

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Default: vpc-03b0687b56e5e4284

  PublicSubnetA:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0c54a03469761cbd2

  PublicSubnetB:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-06743ac42e7cf5ad8

  PrivateSubnetA:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-08fde9a496b874bec

  PrivateSubnetB:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0f75970e73d049f61

  DBUsername:
    Type: String
    Default: admin

  DBPassword:
    Type: String
    NoEcho: true
    Default: Admin123$

  DBName:
    Type: String
    Default: imageapp

  UploadQueueArn:
    Type: String
    Default: arn:aws:sqs:us-east-1:151182332702:akmal-uploads-queue

  NotificationTopicArn:
    Type: String
    Default: arn:aws:sns:us-east-1:151182332702:akmal-uploads-notification

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: akmal-aws-cluster

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess

  ECSServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from ALB on port 8080
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: sg-0b5b0a9bf2a0b9543

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ECS app to access RDS
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref ECSServiceSecurityGroup

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: akmal-alb
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
      SecurityGroups:
        - sg-0b5b0a9bf2a0b9543

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: akmal-tr-group
      VpcId: !Ref VPC
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /actuator/health
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: 200-399

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 8080
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: akmal-task
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: akmal-webapp
          Image: 151182332702.dkr.ecr.us-east-1.amazonaws.com/akmal/webapp:latest
          Essential: true
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: SPRING_DATASOURCE_URL
              Value: !Sub "jdbc:mysql://${MySQLInstance.Endpoint.Address}:3306/${DBName}"
            - Name: DB_USER
              Value: !Ref DBUsername
            - Name: DB_PASSWORD
              Value: !Ref DBPassword
            - Name: DB_PORT
              Value: "3306"
            - Name: AWS_REGION
              Value: "us-east-1"
            - Name: LOAD_BALANCER_HOST
              Value: !GetAtt ALB.DNSName
            - Name: LOAD_BALANCER_PORT
              Value: "8080"
            - Name: SQS_QUEUE_URL
              Value: !Ref UploadQueueArn
            - Name: SNS_TOPIC_ARN
              Value: !Ref NotificationTopicArn

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: ALBListener
    Properties:
      ServiceName: akmal-webapp-service
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 60
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnetA
            - !Ref PublicSubnetB
          SecurityGroups:
            - !Ref ECSServiceSecurityGroup
      LoadBalancers:
        - ContainerName: akmal-webapp
          ContainerPort: 8080
          TargetGroupArn: !Ref ALBTargetGroup

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for MySQL DB
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB

  MySQLInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: 20
      DBInstanceClass: db.t4g.micro
      Engine: mysql
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref AppSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup

Outputs:
  LoadBalancerDNS:
    Description: Public DNS of the application load balancer
    Value: !GetAtt ALB.DNSName
