AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM app for image upload notification (standard deployment, no CodeDeploy)

Resources:
  UploadsNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Akmalkhon-UploadsNotificationFunction
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.12

      # Enable alias-based versioning (safes and production-friendly)
      AutoPublishAlias: live

      Environment:
        Variables:
          TOPIC_ARN: !Ref NotificationTopic
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt UploadQueue.Arn
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
        - SQSPollerPolicy:
            QueueName: !GetAtt UploadQueue.QueueName
        - CloudWatchPutMetricPolicy: {}

  NotificationTopic:
    Type: AWS::SNS::Topic

  UploadQueue:
    Type: AWS::SQS::Queue
